name: GitHub-Runner - Base
on:
  workflow_dispatch:

jobs:
  github-runner-base:
    runs-on: ubuntu-latest
    steps:

      - name: Copy Repo Files
        uses: actions/checkout@master

      - name: Get GitHub organization or user and set variable for docker image creation
        run: |
          VAR_ORG=$(dirname ${GITHUB_REPOSITORY})
          VAR_ORG_LCASE=$(echo $VAR_ORG | tr [:upper:] [:lower:])
          echo 'ORG='$VAR_ORG_LCASE >> $GITHUB_ENV
          echo 'ORG='$VAR_ORG_LCASE

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_SECRET }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.base
          pull: true
          push: true
          tags: ${{ env.ORG }}/github-runner-base:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max